openapi: 3.0.1
info:
  title: myapp
  description: Fampay Backend Assignment
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Videos
    description: Endpoints to access latest youtube videos
  - name: Specification
    description: The swagger API specification
paths:
  /videos:
    get:
      tags:
        - Videos
      description: Fetch paginated videos
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number of the videos to be fetched, starting from 0
      responses:
        200:
          description: Return the paginated videos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
      Video:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        publishedAt:
          type: string
        thumbnails:
          type: object
          properties:
            default: 
              type: string
            high: 
              type: string
      Error:
        type: object
        additionalProperties: true